name: Daily Stock Analysis

on:
  schedule:
    # Run every day at 9:30 AM EST (after market open)
    - cron: '30 14 * * 1-5'  # 14:30 UTC = 9:30 EST on weekdays
  workflow_dispatch:  # Allow manual trigger

jobs:
  analyze-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy yagmail
        
    - name: Run stock analysis
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "EMAIL_ADDRESS = '$EMAIL_ADDRESS'" > config.py
        echo "EMAIL_PASSWORD = '$EMAIL_PASSWORD'" >> config.py
        python NASDAQ-100-2.py